- name: set RHSM subscriptions
  hosts: all
  vars_files:
    - vars/subscriptions.yml

  tasks:
    - name: get subscription pool id for "{{ subscription_name }}"
      command: sh -c "subscription-manager list --available --matches '{{ subscription_name }}' | grep 'Pool ID:' | cut -d':' -f2"
      when: subscription_name is defined
      register: pool_id

    - name: show pool id
      debug:
        msg: "{{ pool_id.stdout }}"
      when: subscription_name is defined

    - name: set subscriptions
      command: "subscription-manager attach --pool {{ pool_id.stdout }}"
      register: result
      when: subscription_name is defined

    - name: show result
      debug: 
        msg: "{{ result.stdout }}"
      when: subscription_name is defined
